services:
  zorgforma-frontend:
    container_name: zorgforma-frontend
    build:
      context: .
      args:
        NEXT_PUBLIC_STRAPI_URL: http://162.55.168.224:1337
        STRAPI_URL_INTERNAL: http://127.0.0.1:1337
    network_mode: "host"
    environment:
      - PORT=3001
      - STRAPI_URL_INTERNAL=http://127.0.0.1:1337
    restart: always
