version: '3'
services:
  zorgforma-strapi:
    container_name: zorgforma-strapi
    build: .
    image: zorgforma-strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: zorgforma-db
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: production
      # Important: JWT Secret and App Keys must be in .env on the server
    volumes:
      - ./config:/opt/app/config
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    depends_on:
      - zorgforma-db
    networks:
      - strapi

  zorgforma-db:
    container_name: zorgforma-db
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: strapi
    volumes:
      - strapi-data:/var/lib/postgresql/data
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
